### ISSUE TITLE
UI issue: "Tools" cannot be listed

### ISSUE THREAD

**Issue by rikumi** [iabem97/houdini-public#18]
"Tools" cannot be listed.
Should change `tools` to `tweaks` in `PackagesViewController.m:289`:

https://github.com/iabem97/houdini-public/blob/efbdb4f3c7600199a0abf9f01ec01614b4d81c40/houdini/View%20Controllers/PackagesViewController.m#L289

**Comment by iabem97** [comment]
Tools is not implemented (yet). Will hide it or disable it in a future release.
Thank you for your note.
