### ISSUE TITLE
IPA link on GitHub and website are just redirects

### ISSUE THREAD

**Issue by belltechdave** [iabem97/houdini-public#19]
Your links for the IPA file on the GitHub and the website are just redirects back to one another and don’t actually provide the IPA.

**Comment by puung1297** [comment]
Right ... I can't download ipa file, too
(I have developer account....)

**Comment by ehsan20000** [comment]
hi , I can't download ipa file, too
(I have developer account....)

**Comment by VinLark** [comment]
You guys need to compile it with Xcode. I assume he made it redirect because he himself didn't have a dev account to compile it.

**Comment by JunyuT** [comment]
Compile it yourselves if you have a paid dev account.
Wait and don't complain or ask for anything if you don't.
