### ISSUE TITLE
screen resolution stuck (iPhone 7+)

### ISSUE THREAD

**Issue by ulyxime** [iabem97/houdini-public#2]
hi !... i mess whit the resolution tweak and now my iPhone is stuck whit huge icons and the app doesn't have a way to reset it ... is there a way to reset the resolution whit ssh or something..

**Comment by Samgisaninja** [comment]
easiest way would be [filzaescaped](https://www.dropbox.com/s/ijm517uw3h3s5hx/FilzaEscaped.ipa?dl=0)
open /User/Library/Preferences/com.apple.iokit.IOMobileGraphicsFamily.plist
set canvas_height to 1511
set canvas_width to 850

**Comment by ulyxime** [comment]
you just fix my stress ! thx allot

**Comment by ulyxime** [comment]
well it didnt work...

**Comment by ulyxime** [comment]
i need a way to acces by ssh i can activate liberios jb that give acces to a ssh server and i can go from there but i try whit filza and it wont save it keep coming back like it was

**Comment by ulyxime** [comment]
FOUND A FIX! it so dumb tho hahahahahaha 
(on your iPhone)
Go in settings
then Display & Brightness
and press on View all the way down 
and you can use that to put back your original setting ...
